// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  Address,
  DataSourceTemplate,
  DataSourceContext
} from "@graphprotocol/graph-ts";

export class ZKERC20 extends DataSourceTemplate {
  
  static createWithAddress(address: Address) {
    DataSourceTemplate.create("ZKERC20", [address.toHex()]);
  }

  static create(name: string, params: Array<string>): void {
    DataSourceTemplate.create("ZKERC20", params);
  }

  static createWithContext(
    name: string,
    params: Array<string>,
    context: DataSourceContext,
  ): void {
    DataSourceTemplate.createWithContext("ZKERC20", params, context)
  }
}
