// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  ethereum,
  JSONValue,
  TypedMap,
  Entity,
  Bytes,
  Address,
  BigInt
} from "@graphprotocol/graph-ts";

export class ConvertTokens extends ethereum.Event {
  get params(): ConvertTokens__Params {
    return new ConvertTokens__Params(this);
  }
}

export class ConvertTokens__Params {
  _event: ConvertTokens;

  constructor(event: ConvertTokens) {
    this._event = event;
  }

  get owner(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get value(): BigInt {
    return this._event.parameters[1].value.toBigInt();
  }
}

export class CreateNote extends ethereum.Event {
  get params(): CreateNote__Params {
    return new CreateNote__Params(this);
  }
}

export class CreateNote__Params {
  _event: CreateNote;

  constructor(event: CreateNote) {
    this._event = event;
  }

  get owner(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get noteHash(): Bytes {
    return this._event.parameters[1].value.toBytes();
  }

  get metadata(): Bytes {
    return this._event.parameters[2].value.toBytes();
  }
}

export class CreateNoteRegistry extends ethereum.Event {
  get params(): CreateNoteRegistry__Params {
    return new CreateNoteRegistry__Params(this);
  }
}

export class CreateNoteRegistry__Params {
  _event: CreateNoteRegistry;

  constructor(event: CreateNoteRegistry) {
    this._event = event;
  }

  get noteRegistryId(): BigInt {
    return this._event.parameters[0].value.toBigInt();
  }
}

export class CreateZkAsset extends ethereum.Event {
  get params(): CreateZkAsset__Params {
    return new CreateZkAsset__Params(this);
  }
}

export class CreateZkAsset__Params {
  _event: CreateZkAsset;

  constructor(event: CreateZkAsset) {
    this._event = event;
  }

  get aceAddress(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get linkedTokenAddress(): Address {
    return this._event.parameters[1].value.toAddress();
  }

  get scalingFactor(): BigInt {
    return this._event.parameters[2].value.toBigInt();
  }

  get _canAdjustSupply(): boolean {
    return this._event.parameters[3].value.toBoolean();
  }

  get _canConvert(): boolean {
    return this._event.parameters[4].value.toBoolean();
  }
}

export class DestroyNote extends ethereum.Event {
  get params(): DestroyNote__Params {
    return new DestroyNote__Params(this);
  }
}

export class DestroyNote__Params {
  _event: DestroyNote;

  constructor(event: DestroyNote) {
    this._event = event;
  }

  get owner(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get noteHash(): Bytes {
    return this._event.parameters[1].value.toBytes();
  }
}

export class Log extends ethereum.Event {
  get params(): Log__Params {
    return new Log__Params(this);
  }
}

export class Log__Params {
  _event: Log;

  constructor(event: Log) {
    this._event = event;
  }

  get owner(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get value(): BigInt {
    return this._event.parameters[1].value.toBigInt();
  }

  get noteHash(): Bytes {
    return this._event.parameters[2].value.toBytes();
  }
}

export class LogString extends ethereum.Event {
  get params(): LogString__Params {
    return new LogString__Params(this);
  }
}

export class LogString__Params {
  _event: LogString;

  constructor(event: LogString) {
    this._event = event;
  }

  get value(): string {
    return this._event.parameters[0].value.toString();
  }
}

export class RedeemTokens extends ethereum.Event {
  get params(): RedeemTokens__Params {
    return new RedeemTokens__Params(this);
  }
}

export class RedeemTokens__Params {
  _event: RedeemTokens;

  constructor(event: RedeemTokens) {
    this._event = event;
  }

  get owner(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get value(): BigInt {
    return this._event.parameters[1].value.toBigInt();
  }
}

export class SetEncryptionPK extends ethereum.Event {
  get params(): SetEncryptionPK__Params {
    return new SetEncryptionPK__Params(this);
  }
}

export class SetEncryptionPK__Params {
  _event: SetEncryptionPK;

  constructor(event: SetEncryptionPK) {
    this._event = event;
  }

  get userAddress(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get encryptionPK(): Bytes {
    return this._event.parameters[1].value.toBytes();
  }
}

export class UpdateNoteMetaData extends ethereum.Event {
  get params(): UpdateNoteMetaData__Params {
    return new UpdateNoteMetaData__Params(this);
  }
}

export class UpdateNoteMetaData__Params {
  _event: UpdateNoteMetaData;

  constructor(event: UpdateNoteMetaData) {
    this._event = event;
  }

  get owner(): Address {
    return this._event.parameters[0].value.toAddress();
  }

  get noteHash(): Bytes {
    return this._event.parameters[1].value.toBytes();
  }

  get metadata(): Bytes {
    return this._event.parameters[2].value.toBytes();
  }
}

export class ZKERC20 extends ethereum.SmartContract {
  static bind(address: Address): ZKERC20 {
    return new ZKERC20("ZKERC20", address);
  }

  BURN_PROOF(): i32 {
    let result = super.call("BURN_PROOF", "BURN_PROOF():(uint24)", []);

    return result[0].toI32();
  }

  try_BURN_PROOF(): ethereum.CallResult<i32> {
    let result = super.tryCall("BURN_PROOF", "BURN_PROOF():(uint24)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toI32());
  }

  DIVIDEND_PROOF(): i32 {
    let result = super.call("DIVIDEND_PROOF", "DIVIDEND_PROOF():(uint24)", []);

    return result[0].toI32();
  }

  try_DIVIDEND_PROOF(): ethereum.CallResult<i32> {
    let result = super.tryCall(
      "DIVIDEND_PROOF",
      "DIVIDEND_PROOF():(uint24)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toI32());
  }

  EIP712_DOMAIN_HASH(): Bytes {
    let result = super.call(
      "EIP712_DOMAIN_HASH",
      "EIP712_DOMAIN_HASH():(bytes32)",
      []
    );

    return result[0].toBytes();
  }

  try_EIP712_DOMAIN_HASH(): ethereum.CallResult<Bytes> {
    let result = super.tryCall(
      "EIP712_DOMAIN_HASH",
      "EIP712_DOMAIN_HASH():(bytes32)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBytes());
  }

  JOIN_SPLIT_PROOF(): i32 {
    let result = super.call(
      "JOIN_SPLIT_PROOF",
      "JOIN_SPLIT_PROOF():(uint24)",
      []
    );

    return result[0].toI32();
  }

  try_JOIN_SPLIT_PROOF(): ethereum.CallResult<i32> {
    let result = super.tryCall(
      "JOIN_SPLIT_PROOF",
      "JOIN_SPLIT_PROOF():(uint24)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toI32());
  }

  MINT_PROOF(): i32 {
    let result = super.call("MINT_PROOF", "MINT_PROOF():(uint24)", []);

    return result[0].toI32();
  }

  try_MINT_PROOF(): ethereum.CallResult<i32> {
    let result = super.tryCall("MINT_PROOF", "MINT_PROOF():(uint24)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toI32());
  }

  PRIVATE_RANGE_PROOF(): i32 {
    let result = super.call(
      "PRIVATE_RANGE_PROOF",
      "PRIVATE_RANGE_PROOF():(uint24)",
      []
    );

    return result[0].toI32();
  }

  try_PRIVATE_RANGE_PROOF(): ethereum.CallResult<i32> {
    let result = super.tryCall(
      "PRIVATE_RANGE_PROOF",
      "PRIVATE_RANGE_PROOF():(uint24)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toI32());
  }

  PUBLIC_RANGE_PROOF(): i32 {
    let result = super.call(
      "PUBLIC_RANGE_PROOF",
      "PUBLIC_RANGE_PROOF():(uint24)",
      []
    );

    return result[0].toI32();
  }

  try_PUBLIC_RANGE_PROOF(): ethereum.CallResult<i32> {
    let result = super.tryCall(
      "PUBLIC_RANGE_PROOF",
      "PUBLIC_RANGE_PROOF():(uint24)",
      []
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toI32());
  }

  ace(): Address {
    let result = super.call("ace", "ace():(address)", []);

    return result[0].toAddress();
  }

  try_ace(): ethereum.CallResult<Address> {
    let result = super.tryCall("ace", "ace():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  confidentialApproved(param0: Bytes, param1: Address): boolean {
    let result = super.call(
      "confidentialApproved",
      "confidentialApproved(bytes32,address):(bool)",
      [
        ethereum.Value.fromFixedBytes(param0),
        ethereum.Value.fromAddress(param1)
      ]
    );

    return result[0].toBoolean();
  }

  try_confidentialApproved(
    param0: Bytes,
    param1: Address
  ): ethereum.CallResult<boolean> {
    let result = super.tryCall(
      "confidentialApproved",
      "confidentialApproved(bytes32,address):(bool)",
      [
        ethereum.Value.fromFixedBytes(param0),
        ethereum.Value.fromAddress(param1)
      ]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }

  erc20Address(): Address {
    let result = super.call("erc20Address", "erc20Address():(address)", []);

    return result[0].toAddress();
  }

  try_erc20Address(): ethereum.CallResult<Address> {
    let result = super.tryCall("erc20Address", "erc20Address():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  linkedToken(): Address {
    let result = super.call("linkedToken", "linkedToken():(address)", []);

    return result[0].toAddress();
  }

  try_linkedToken(): ethereum.CallResult<Address> {
    let result = super.tryCall("linkedToken", "linkedToken():(address)", []);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toAddress());
  }

  metaDataTimeLog(param0: Bytes): BigInt {
    let result = super.call(
      "metaDataTimeLog",
      "metaDataTimeLog(bytes32):(uint256)",
      [ethereum.Value.fromFixedBytes(param0)]
    );

    return result[0].toBigInt();
  }

  try_metaDataTimeLog(param0: Bytes): ethereum.CallResult<BigInt> {
    let result = super.tryCall(
      "metaDataTimeLog",
      "metaDataTimeLog(bytes32):(uint256)",
      [ethereum.Value.fromFixedBytes(param0)]
    );
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  noteAccess(param0: Bytes): BigInt {
    let result = super.call("noteAccess", "noteAccess(bytes32):(uint256)", [
      ethereum.Value.fromFixedBytes(param0)
    ]);

    return result[0].toBigInt();
  }

  try_noteAccess(param0: Bytes): ethereum.CallResult<BigInt> {
    let result = super.tryCall("noteAccess", "noteAccess(bytes32):(uint256)", [
      ethereum.Value.fromFixedBytes(param0)
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBigInt());
  }

  signatureLog(param0: Bytes): boolean {
    let result = super.call("signatureLog", "signatureLog(bytes32):(bool)", [
      ethereum.Value.fromFixedBytes(param0)
    ]);

    return result[0].toBoolean();
  }

  try_signatureLog(param0: Bytes): ethereum.CallResult<boolean> {
    let result = super.tryCall("signatureLog", "signatureLog(bytes32):(bool)", [
      ethereum.Value.fromFixedBytes(param0)
    ]);
    if (result.reverted) {
      return new ethereum.CallResult();
    }
    let value = result.value;
    return ethereum.CallResult.fromValue(value[0].toBoolean());
  }
}

export class ConstructorCall extends ethereum.Call {
  get inputs(): ConstructorCall__Inputs {
    return new ConstructorCall__Inputs(this);
  }

  get outputs(): ConstructorCall__Outputs {
    return new ConstructorCall__Outputs(this);
  }
}

export class ConstructorCall__Inputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }

  get _aceAddress(): Address {
    return this._call.inputValues[0].value.toAddress();
  }

  get _erc20Address(): Address {
    return this._call.inputValues[1].value.toAddress();
  }
}

export class ConstructorCall__Outputs {
  _call: ConstructorCall;

  constructor(call: ConstructorCall) {
    this._call = call;
  }
}

export class ApproveProofCall extends ethereum.Call {
  get inputs(): ApproveProofCall__Inputs {
    return new ApproveProofCall__Inputs(this);
  }

  get outputs(): ApproveProofCall__Outputs {
    return new ApproveProofCall__Outputs(this);
  }
}

export class ApproveProofCall__Inputs {
  _call: ApproveProofCall;

  constructor(call: ApproveProofCall) {
    this._call = call;
  }

  get _proofId(): i32 {
    return this._call.inputValues[0].value.toI32();
  }

  get _proofOutputs(): Bytes {
    return this._call.inputValues[1].value.toBytes();
  }

  get _spender(): Address {
    return this._call.inputValues[2].value.toAddress();
  }

  get _approval(): boolean {
    return this._call.inputValues[3].value.toBoolean();
  }

  get _proofSignature(): Bytes {
    return this._call.inputValues[4].value.toBytes();
  }
}

export class ApproveProofCall__Outputs {
  _call: ApproveProofCall;

  constructor(call: ApproveProofCall) {
    this._call = call;
  }
}

export class ConfidentialApproveCall extends ethereum.Call {
  get inputs(): ConfidentialApproveCall__Inputs {
    return new ConfidentialApproveCall__Inputs(this);
  }

  get outputs(): ConfidentialApproveCall__Outputs {
    return new ConfidentialApproveCall__Outputs(this);
  }
}

export class ConfidentialApproveCall__Inputs {
  _call: ConfidentialApproveCall;

  constructor(call: ConfidentialApproveCall) {
    this._call = call;
  }

  get _noteHash(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }

  get _spender(): Address {
    return this._call.inputValues[1].value.toAddress();
  }

  get _spenderApproval(): boolean {
    return this._call.inputValues[2].value.toBoolean();
  }

  get _signature(): Bytes {
    return this._call.inputValues[3].value.toBytes();
  }
}

export class ConfidentialApproveCall__Outputs {
  _call: ConfidentialApproveCall;

  constructor(call: ConfidentialApproveCall) {
    this._call = call;
  }
}

export class ConfidentialTransferCall extends ethereum.Call {
  get inputs(): ConfidentialTransferCall__Inputs {
    return new ConfidentialTransferCall__Inputs(this);
  }

  get outputs(): ConfidentialTransferCall__Outputs {
    return new ConfidentialTransferCall__Outputs(this);
  }
}

export class ConfidentialTransferCall__Inputs {
  _call: ConfidentialTransferCall;

  constructor(call: ConfidentialTransferCall) {
    this._call = call;
  }

  get _proofId(): i32 {
    return this._call.inputValues[0].value.toI32();
  }

  get _proofData(): Bytes {
    return this._call.inputValues[1].value.toBytes();
  }

  get _signatures(): Bytes {
    return this._call.inputValues[2].value.toBytes();
  }
}

export class ConfidentialTransferCall__Outputs {
  _call: ConfidentialTransferCall;

  constructor(call: ConfidentialTransferCall) {
    this._call = call;
  }
}

export class ConfidentialTransfer1Call extends ethereum.Call {
  get inputs(): ConfidentialTransfer1Call__Inputs {
    return new ConfidentialTransfer1Call__Inputs(this);
  }

  get outputs(): ConfidentialTransfer1Call__Outputs {
    return new ConfidentialTransfer1Call__Outputs(this);
  }
}

export class ConfidentialTransfer1Call__Inputs {
  _call: ConfidentialTransfer1Call;

  constructor(call: ConfidentialTransfer1Call) {
    this._call = call;
  }

  get _proofData(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }

  get _signatures(): Bytes {
    return this._call.inputValues[1].value.toBytes();
  }
}

export class ConfidentialTransfer1Call__Outputs {
  _call: ConfidentialTransfer1Call;

  constructor(call: ConfidentialTransfer1Call) {
    this._call = call;
  }
}

export class ConfidentialTransferFromCall extends ethereum.Call {
  get inputs(): ConfidentialTransferFromCall__Inputs {
    return new ConfidentialTransferFromCall__Inputs(this);
  }

  get outputs(): ConfidentialTransferFromCall__Outputs {
    return new ConfidentialTransferFromCall__Outputs(this);
  }
}

export class ConfidentialTransferFromCall__Inputs {
  _call: ConfidentialTransferFromCall;

  constructor(call: ConfidentialTransferFromCall) {
    this._call = call;
  }

  get _proof(): i32 {
    return this._call.inputValues[0].value.toI32();
  }

  get _proofOutput(): Bytes {
    return this._call.inputValues[1].value.toBytes();
  }
}

export class ConfidentialTransferFromCall__Outputs {
  _call: ConfidentialTransferFromCall;

  constructor(call: ConfidentialTransferFromCall) {
    this._call = call;
  }
}

export class SetEncryptionPKCall extends ethereum.Call {
  get inputs(): SetEncryptionPKCall__Inputs {
    return new SetEncryptionPKCall__Inputs(this);
  }

  get outputs(): SetEncryptionPKCall__Outputs {
    return new SetEncryptionPKCall__Outputs(this);
  }
}

export class SetEncryptionPKCall__Inputs {
  _call: SetEncryptionPKCall;

  constructor(call: SetEncryptionPKCall) {
    this._call = call;
  }

  get encryptionPK(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }
}

export class SetEncryptionPKCall__Outputs {
  _call: SetEncryptionPKCall;

  constructor(call: SetEncryptionPKCall) {
    this._call = call;
  }
}

export class UpdateNoteMetaDataCall extends ethereum.Call {
  get inputs(): UpdateNoteMetaDataCall__Inputs {
    return new UpdateNoteMetaDataCall__Inputs(this);
  }

  get outputs(): UpdateNoteMetaDataCall__Outputs {
    return new UpdateNoteMetaDataCall__Outputs(this);
  }
}

export class UpdateNoteMetaDataCall__Inputs {
  _call: UpdateNoteMetaDataCall;

  constructor(call: UpdateNoteMetaDataCall) {
    this._call = call;
  }

  get noteHash(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }

  get metaData(): Bytes {
    return this._call.inputValues[1].value.toBytes();
  }
}

export class UpdateNoteMetaDataCall__Outputs {
  _call: UpdateNoteMetaDataCall;

  constructor(call: UpdateNoteMetaDataCall) {
    this._call = call;
  }
}

export class ApproveAceToSpendTokensCall extends ethereum.Call {
  get inputs(): ApproveAceToSpendTokensCall__Inputs {
    return new ApproveAceToSpendTokensCall__Inputs(this);
  }

  get outputs(): ApproveAceToSpendTokensCall__Outputs {
    return new ApproveAceToSpendTokensCall__Outputs(this);
  }
}

export class ApproveAceToSpendTokensCall__Inputs {
  _call: ApproveAceToSpendTokensCall;

  constructor(call: ApproveAceToSpendTokensCall) {
    this._call = call;
  }

  get _proofHash(): Bytes {
    return this._call.inputValues[0].value.toBytes();
  }

  get _value(): BigInt {
    return this._call.inputValues[1].value.toBigInt();
  }
}

export class ApproveAceToSpendTokensCall__Outputs {
  _call: ApproveAceToSpendTokensCall;

  constructor(call: ApproveAceToSpendTokensCall) {
    this._call = call;
  }
}
